---
- name: checking installation
  include: check.yaml

- name: install envoy
  include: install.yaml
  when: envoy_client_version.stdout != envoy_server_version or envoy_client_version.stdout | length == 0

- name: config envoy
  include: config.yaml