--- 
- name: setup ip internal kubelet
  template:
    src: kubelet_sysconfig.j2
    dest: /etc/sysconfig/kubelet
    owner: root
    group: root
    mode: 0644

- name: run master config
  include: config-master.yml
  when:  type == "Master"

- name: run node config
  include: master-worker/join.yaml
  when: type != "Master"

- name: create directory
  file:
    path: /tmp/kube-apply
    state: directory
    owner: root
    group: root
    mode: 0755
